### ISSUE TITLE
Context Action (warning) on `use This::Module`

### ISSUE THREAD

**Issue by librasteve** [ab5tract/comma-plugin#10]
When I am working on a module with Comma plugin, I get a yellow squiggly and a context action when I use the current module.

I am working on Functional::HTML

I have this code:

```raku
#!/usr/bin/env raku
use v6.d;

use HTML::Functional;    #<== get yellow squiggly here

my $head = head [
    meta( :charset<utf-8> ),
...

```

MeTA6.json:

```json
{
    "name": "HTML::Functional",
    "description": "blah blah blah",
    "version": "0.0.2",
    "authors": [
        "librasteve"
    ],
    "auth": "zef:librasteve",
    "build-depends": [],     #<== FIX puts HTML::Functional here!
    "provides": {
        "HTML::Functional": "lib/HTML/Functional.rakumod"
    },
    "license": "Artistic-2.0",
    "source-url": "https://github.com/librasteve/raku-HTML-Functional.git"
}
```

Right now my workaround is to disable this inspection at Editor > Inspections (search Raku)

There are two issues with this:

1. Early on I prefer not to go `zef install . --force-install` to install the wip module [but I accept that this is suboptimal practice and maybe I should adjust my workflow]
2. The FIX is to insert the current module in the DEPENDS section of the META6.json, so I end up depending on my own wip module!

My ideal would be to always exclude the current wip module from the inspection, or at least to be able to configure to exclude it without disabling all module present checks.

The fix should check if this use is the provides module and maybe advise to disable provides from the inspection of tell you to `zef install .`

![Screenshot 2024-10-21 at 17 08 40](https://github.com/user-attachments/assets/88fcd2cc-5666-4e6d-b9e8-a9440e04e5c0)

**Comment by ab5tract** [comment]
Thanks for reporting! This should be fixed in beta 21, along with dependency management (`zef` only for now) in general.

Please let me know either way if this is fixed or still a problem for you.

**Comment by librasteve** [comment]
Sounds good - I will close for now (and re-open if not actually fixed)
