### ISSUE TITLE
Raku meta file is missing (not raku project)

### ISSUE THREAD

**Issue by librasteve** [ab5tract/comma-plugin#15]
I am using Comma Plugin 2.0 in the latest IntelliJ IDEA Universal.

I create a new Python project and get the error:

```Raku meta file is missing```

So I suggest that the plugin is too earnest and should only flag this error if this is a new Raku project.

**Comment by ab5tract** [comment]
Indeed. Currently this is the mechanism for checking whether this is a new Raku project. I'll have to think a bit on how to manage this, as it is also an issue for Raku script-only projects as they do not create/expect a `META6.json` either.

**Comment by ab5tract** [comment]
I'm going to assume that this one has been successfully addressed. Please re-open if you experience this again!
