### ISSUE TITLE
No crotmp Syntax Highlighting

### ISSUE THREAD

**Issue by librasteve** [ab5tract/comma-plugin#25]
When opening a .crotmp file there is no syntax highlighting.

Under `CMD+,` (open setting) > Editor > File Types there is no entry under `Cro::HTTP::WebApp template`

This is a regression vs. final Comma Complete and maybe a regression against recent comma-plugin iterations.

All the raku file types are working fine.

Expected:
<img width="1044" alt="Screenshot 2024-11-20 at 17 46 14" src="https://github.com/user-attachments/assets/09d284d9-811d-4dcb-b32e-172d39a649a7">

Got:
![Screenshot 2024-11-20 at 17 54 07](https://github.com/user-attachments/assets/eb833137-840a-45c2-a0e2-937f28877682)

**Comment by ab5tract** [comment]
This is expected in `comma-plugin` as I have avoided everything related to Cro. 

Please see #21 and add any remaining missing Cro-related functionalities to the checklist in this ticket.

**Comment by ab5tract** [comment]
@librasteve This should be addressed in [beta 31](https://github.com/ab5tract/comma-plugin/releases/tag/v2.0-beta.31)

**Comment by librasteve** [comment]
oh - I see that explains it - I'll close this issue for now

I'm hoping to add [Fragment](https://github.com/croservices/cro-webapp/pull/91) highlighting (a new Cro::WebApp::Template feature)
