### ISSUE TITLE
strange entries in "external libraries" tree

### ISSUE THREAD

**Issue by timo** [ab5tract/comma-plugin#6]
![image](https://github.com/user-attachments/assets/966f3ac2-7f1d-4147-ac32-0bb3fdc97096)

I have a `/-120340557:{name => {by-distro.name => { => , mswin32 => Win32::Registry}}}!/` that i'm not sure where it came from, and i'm not sure how to ask IDEA what it thinks that is

**Comment by ab5tract** [comment]
Yeah, this one is a definite mystery. I'll poke at this now that I've gotten the SDK stuff addressed.

**Comment by ab5tract** [comment]
I've fixed this in the specific case, but will need to look into how things are generally handled by `zef` when dealing with OS-specific dependencies.

**Comment by ab5tract** [comment]
This particular expression of the problem is fixed. However, dependencies that don't apply to the user's distro may still appear.
