### ISSUE TITLE
Empty files or IDE hangs when looking at sources from installed modules

### ISSUE THREAD

**Issue by timo** [ab5tract/comma-plugin#7]
![image](https://github.com/user-attachments/assets/24b27c0a-c735-411b-85e9-4999f2db6db0)

Comma told me that it can't find the sub "ddt", so I went looking. ctrl-clicking on the name in the "use" statement has the same effect as double-clicking in the "external libraries" tree: either i get an empty file, or i see the source, but it's not highlighted, and the IDE freezes, apparently forever.

**Comment by ab5tract** [comment]
I can say that this has been extensively poked at and -- hopefully -- fixed in entirety. Please re-open if you run into any other expressions of this.
