### ISSUE TITLE
Missing libraries/modules? clicking "use Test" gives "No usages found in Project Files"

### ISSUE THREAD

**Issue by timo** [ab5tract/comma-plugin#8]
![image](https://github.com/user-attachments/assets/e1fa6675-a872-4a98-82c0-5d73fa4ca2f4)

Test is also not visible in the "external libraries" tree

**Comment by ab5tract** [comment]
`Test` is an interesting one because it's a rare example of a module provided by Rakudo that also requires a `use` statement.

I'm not actually sure the best way to resolve this but will look into it.

**Comment by ab5tract** [comment]
This should be fixed as of cdb2030993939b039ed509be7fc84cd84126abfa / beta 22.
